# Traces the live white raster logo (797x209 PNG, the only file gasrec.co.uk publishes) into a single-colour SVG path.
# Usage: python3 scripts/logo.py   (needs Pillow and potracer; run `npm run media` first)
import potrace
from PIL import Image

im = Image.open("_scrape/orig/logo.png").convert("RGBA")
# The PNG carries a 1px opaque frame around its edge; drop it so only the letters are traced.
im = im.crop((3, 3, im.width - 3, im.height - 3))
scale = 3
im = im.resize((im.width * scale, im.height * scale), Image.LANCZOS)
alpha = im.split()[3]
# potracer treats falsy pixels as ink, so the test is inverted.
bitmap = potrace.Bitmap([[alpha.getpixel((x, y)) <= 128 for x in range(im.width)] for y in range(im.height)])
path = bitmap.trace(turdsize=20, alphamax=1.0, opticurve=True, opttolerance=0.2)

def f(v): return f"{v / scale:.2f}".rstrip("0").rstrip(".")
# The wordmark is two-tone on Gasrec's vehicles and signage ("gas" blue, "rec" green), so the subpaths are split
# at the gap between the "s" and the "r" (x = SPLIT in the traced PNG's pixels).
SPLIT = 400
parts = {"gas": [], "rec": []}
for curve in path:
    d = parts["gas" if curve.start_point.x / scale < SPLIT else "rec"]
    d.append(f"M{f(curve.start_point.x)} {f(curve.start_point.y)}")
    for seg in curve.segments:
        if seg.is_corner:
            d.append(f"L{f(seg.c.x)} {f(seg.c.y)}L{f(seg.end_point.x)} {f(seg.end_point.y)}")
        else:
            d.append(f"C{f(seg.c1.x)} {f(seg.c1.y)} {f(seg.c2.x)} {f(seg.c2.y)} {f(seg.end_point.x)} {f(seg.end_point.y)}")
    d.append("Z")
gas, rec = "".join(parts["gas"]), "".join(parts["rec"])
bbox = alpha.point(lambda v: 255 if v > 128 else 0).getbbox()
x0, y0, x1, y1 = [v / scale for v in bbox]
view = f"{x0:.0f} {y0:.0f} {x1 - x0:.0f} {y1 - y0:.0f}"
svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}"><path fill="#fff" fill-rule="evenodd" d="{gas}{rec}"/></svg>'
open("public/brand/logo.svg", "w").write(svg)
open("lib/logo.ts", "w").write(f'// Generated by scripts/logo.py from the live white logo PNG.\nexport const logoViewBox = "{view}";\nexport const logoGas = "{gas}";\nexport const logoRec = "{rec}";\n')
print(view, len(svg))
